apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kss1cuo8h-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:a4413d5bd70277382301aaa10b9cd3313dce8806@sha256:a3bef249fe94ca67e003fb2bfa2eeffd3327ab97018a24e79e6fb90c5a04c3ec
          name: container-image
